package com.sg.cp.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DrevExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public DrevExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDrevidIsNull() {
            addCriterion("drevid is null");
            return (Criteria) this;
        }

        public Criteria andDrevidIsNotNull() {
            addCriterion("drevid is not null");
            return (Criteria) this;
        }

        public Criteria andDrevidEqualTo(Integer value) {
            addCriterion("drevid =", value, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidNotEqualTo(Integer value) {
            addCriterion("drevid <>", value, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidGreaterThan(Integer value) {
            addCriterion("drevid >", value, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidGreaterThanOrEqualTo(Integer value) {
            addCriterion("drevid >=", value, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidLessThan(Integer value) {
            addCriterion("drevid <", value, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidLessThanOrEqualTo(Integer value) {
            addCriterion("drevid <=", value, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidIn(List<Integer> values) {
            addCriterion("drevid in", values, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidNotIn(List<Integer> values) {
            addCriterion("drevid not in", values, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidBetween(Integer value1, Integer value2) {
            addCriterion("drevid between", value1, value2, "drevid");
            return (Criteria) this;
        }

        public Criteria andDrevidNotBetween(Integer value1, Integer value2) {
            addCriterion("drevid not between", value1, value2, "drevid");
            return (Criteria) this;
        }

        public Criteria andTransdateIsNull() {
            addCriterion("transdate is null");
            return (Criteria) this;
        }

        public Criteria andTransdateIsNotNull() {
            addCriterion("transdate is not null");
            return (Criteria) this;
        }

        public Criteria andTransdateEqualTo(Date value) {
            addCriterion("transdate =", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateNotEqualTo(Date value) {
            addCriterion("transdate <>", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateGreaterThan(Date value) {
            addCriterion("transdate >", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateGreaterThanOrEqualTo(Date value) {
            addCriterion("transdate >=", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateLessThan(Date value) {
            addCriterion("transdate <", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateLessThanOrEqualTo(Date value) {
            addCriterion("transdate <=", value, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateIn(List<Date> values) {
            addCriterion("transdate in", values, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateNotIn(List<Date> values) {
            addCriterion("transdate not in", values, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateBetween(Date value1, Date value2) {
            addCriterion("transdate between", value1, value2, "transdate");
            return (Criteria) this;
        }

        public Criteria andTransdateNotBetween(Date value1, Date value2) {
            addCriterion("transdate not between", value1, value2, "transdate");
            return (Criteria) this;
        }

        public Criteria andItemidIsNull() {
            addCriterion("itemid is null");
            return (Criteria) this;
        }

        public Criteria andItemidIsNotNull() {
            addCriterion("itemid is not null");
            return (Criteria) this;
        }

        public Criteria andItemidEqualTo(Integer value) {
            addCriterion("itemid =", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotEqualTo(Integer value) {
            addCriterion("itemid <>", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidGreaterThan(Integer value) {
            addCriterion("itemid >", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemid >=", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidLessThan(Integer value) {
            addCriterion("itemid <", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidLessThanOrEqualTo(Integer value) {
            addCriterion("itemid <=", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidIn(List<Integer> values) {
            addCriterion("itemid in", values, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotIn(List<Integer> values) {
            addCriterion("itemid not in", values, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidBetween(Integer value1, Integer value2) {
            addCriterion("itemid between", value1, value2, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotBetween(Integer value1, Integer value2) {
            addCriterion("itemid not between", value1, value2, "itemid");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNull() {
            addCriterion("totalamt is null");
            return (Criteria) this;
        }

        public Criteria andTotalamtIsNotNull() {
            addCriterion("totalamt is not null");
            return (Criteria) this;
        }

        public Criteria andTotalamtEqualTo(BigDecimal value) {
            addCriterion("totalamt =", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotEqualTo(BigDecimal value) {
            addCriterion("totalamt <>", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThan(BigDecimal value) {
            addCriterion("totalamt >", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("totalamt >=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThan(BigDecimal value) {
            addCriterion("totalamt <", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("totalamt <=", value, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtIn(List<BigDecimal> values) {
            addCriterion("totalamt in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotIn(List<BigDecimal> values) {
            addCriterion("totalamt not in", values, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalamt between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andTotalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalamt not between", value1, value2, "totalamt");
            return (Criteria) this;
        }

        public Criteria andDailyrevIsNull() {
            addCriterion("dailyrev is null");
            return (Criteria) this;
        }

        public Criteria andDailyrevIsNotNull() {
            addCriterion("dailyrev is not null");
            return (Criteria) this;
        }

        public Criteria andDailyrevEqualTo(BigDecimal value) {
            addCriterion("dailyrev =", value, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevNotEqualTo(BigDecimal value) {
            addCriterion("dailyrev <>", value, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevGreaterThan(BigDecimal value) {
            addCriterion("dailyrev >", value, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dailyrev >=", value, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevLessThan(BigDecimal value) {
            addCriterion("dailyrev <", value, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dailyrev <=", value, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevIn(List<BigDecimal> values) {
            addCriterion("dailyrev in", values, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevNotIn(List<BigDecimal> values) {
            addCriterion("dailyrev not in", values, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dailyrev between", value1, value2, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andDailyrevNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dailyrev not between", value1, value2, "dailyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevIsNull() {
            addCriterion("monthlyrev is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevIsNotNull() {
            addCriterion("monthlyrev is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevEqualTo(BigDecimal value) {
            addCriterion("monthlyrev =", value, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevNotEqualTo(BigDecimal value) {
            addCriterion("monthlyrev <>", value, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevGreaterThan(BigDecimal value) {
            addCriterion("monthlyrev >", value, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("monthlyrev >=", value, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevLessThan(BigDecimal value) {
            addCriterion("monthlyrev <", value, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevLessThanOrEqualTo(BigDecimal value) {
            addCriterion("monthlyrev <=", value, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevIn(List<BigDecimal> values) {
            addCriterion("monthlyrev in", values, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevNotIn(List<BigDecimal> values) {
            addCriterion("monthlyrev not in", values, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthlyrev between", value1, value2, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthlyrevNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthlyrev not between", value1, value2, "monthlyrev");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffIsNull() {
            addCriterion("monthcutoff is null");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffIsNotNull() {
            addCriterion("monthcutoff is not null");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffEqualTo(Integer value) {
            addCriterion("monthcutoff =", value, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffNotEqualTo(Integer value) {
            addCriterion("monthcutoff <>", value, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffGreaterThan(Integer value) {
            addCriterion("monthcutoff >", value, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffGreaterThanOrEqualTo(Integer value) {
            addCriterion("monthcutoff >=", value, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffLessThan(Integer value) {
            addCriterion("monthcutoff <", value, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffLessThanOrEqualTo(Integer value) {
            addCriterion("monthcutoff <=", value, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffIn(List<Integer> values) {
            addCriterion("monthcutoff in", values, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffNotIn(List<Integer> values) {
            addCriterion("monthcutoff not in", values, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffBetween(Integer value1, Integer value2) {
            addCriterion("monthcutoff between", value1, value2, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andMonthcutoffNotBetween(Integer value1, Integer value2) {
            addCriterion("monthcutoff not between", value1, value2, "monthcutoff");
            return (Criteria) this;
        }

        public Criteria andPrdrevIsNull() {
            addCriterion("prdrev is null");
            return (Criteria) this;
        }

        public Criteria andPrdrevIsNotNull() {
            addCriterion("prdrev is not null");
            return (Criteria) this;
        }

        public Criteria andPrdrevEqualTo(BigDecimal value) {
            addCriterion("prdrev =", value, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevNotEqualTo(BigDecimal value) {
            addCriterion("prdrev <>", value, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevGreaterThan(BigDecimal value) {
            addCriterion("prdrev >", value, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("prdrev >=", value, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevLessThan(BigDecimal value) {
            addCriterion("prdrev <", value, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevLessThanOrEqualTo(BigDecimal value) {
            addCriterion("prdrev <=", value, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevIn(List<BigDecimal> values) {
            addCriterion("prdrev in", values, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevNotIn(List<BigDecimal> values) {
            addCriterion("prdrev not in", values, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prdrev between", value1, value2, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdrevNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("prdrev not between", value1, value2, "prdrev");
            return (Criteria) this;
        }

        public Criteria andPrdstartIsNull() {
            addCriterion("prdstart is null");
            return (Criteria) this;
        }

        public Criteria andPrdstartIsNotNull() {
            addCriterion("prdstart is not null");
            return (Criteria) this;
        }

        public Criteria andPrdstartEqualTo(Date value) {
            addCriterion("prdstart =", value, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartNotEqualTo(Date value) {
            addCriterion("prdstart <>", value, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartGreaterThan(Date value) {
            addCriterion("prdstart >", value, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartGreaterThanOrEqualTo(Date value) {
            addCriterion("prdstart >=", value, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartLessThan(Date value) {
            addCriterion("prdstart <", value, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartLessThanOrEqualTo(Date value) {
            addCriterion("prdstart <=", value, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartIn(List<Date> values) {
            addCriterion("prdstart in", values, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartNotIn(List<Date> values) {
            addCriterion("prdstart not in", values, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartBetween(Date value1, Date value2) {
            addCriterion("prdstart between", value1, value2, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdstartNotBetween(Date value1, Date value2) {
            addCriterion("prdstart not between", value1, value2, "prdstart");
            return (Criteria) this;
        }

        public Criteria andPrdendIsNull() {
            addCriterion("prdend is null");
            return (Criteria) this;
        }

        public Criteria andPrdendIsNotNull() {
            addCriterion("prdend is not null");
            return (Criteria) this;
        }

        public Criteria andPrdendEqualTo(Date value) {
            addCriterion("prdend =", value, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendNotEqualTo(Date value) {
            addCriterion("prdend <>", value, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendGreaterThan(Date value) {
            addCriterion("prdend >", value, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendGreaterThanOrEqualTo(Date value) {
            addCriterion("prdend >=", value, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendLessThan(Date value) {
            addCriterion("prdend <", value, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendLessThanOrEqualTo(Date value) {
            addCriterion("prdend <=", value, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendIn(List<Date> values) {
            addCriterion("prdend in", values, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendNotIn(List<Date> values) {
            addCriterion("prdend not in", values, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendBetween(Date value1, Date value2) {
            addCriterion("prdend between", value1, value2, "prdend");
            return (Criteria) this;
        }

        public Criteria andPrdendNotBetween(Date value1, Date value2) {
            addCriterion("prdend not between", value1, value2, "prdend");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCredateIsNull() {
            addCriterion("credate is null");
            return (Criteria) this;
        }

        public Criteria andCredateIsNotNull() {
            addCriterion("credate is not null");
            return (Criteria) this;
        }

        public Criteria andCredateEqualTo(Date value) {
            addCriterion("credate =", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateNotEqualTo(Date value) {
            addCriterion("credate <>", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateGreaterThan(Date value) {
            addCriterion("credate >", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateGreaterThanOrEqualTo(Date value) {
            addCriterion("credate >=", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateLessThan(Date value) {
            addCriterion("credate <", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateLessThanOrEqualTo(Date value) {
            addCriterion("credate <=", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateIn(List<Date> values) {
            addCriterion("credate in", values, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateNotIn(List<Date> values) {
            addCriterion("credate not in", values, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateBetween(Date value1, Date value2) {
            addCriterion("credate between", value1, value2, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateNotBetween(Date value1, Date value2) {
            addCriterion("credate not between", value1, value2, "credate");
            return (Criteria) this;
        }

        public Criteria andLupdateIsNull() {
            addCriterion("lupdate is null");
            return (Criteria) this;
        }

        public Criteria andLupdateIsNotNull() {
            addCriterion("lupdate is not null");
            return (Criteria) this;
        }

        public Criteria andLupdateEqualTo(Date value) {
            addCriterion("lupdate =", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateNotEqualTo(Date value) {
            addCriterion("lupdate <>", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateGreaterThan(Date value) {
            addCriterion("lupdate >", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateGreaterThanOrEqualTo(Date value) {
            addCriterion("lupdate >=", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateLessThan(Date value) {
            addCriterion("lupdate <", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateLessThanOrEqualTo(Date value) {
            addCriterion("lupdate <=", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateIn(List<Date> values) {
            addCriterion("lupdate in", values, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateNotIn(List<Date> values) {
            addCriterion("lupdate not in", values, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateBetween(Date value1, Date value2) {
            addCriterion("lupdate between", value1, value2, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateNotBetween(Date value1, Date value2) {
            addCriterion("lupdate not between", value1, value2, "lupdate");
            return (Criteria) this;
        }

        public Criteria andCrebyIsNull() {
            addCriterion("creby is null");
            return (Criteria) this;
        }

        public Criteria andCrebyIsNotNull() {
            addCriterion("creby is not null");
            return (Criteria) this;
        }

        public Criteria andCrebyEqualTo(String value) {
            addCriterion("creby =", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotEqualTo(String value) {
            addCriterion("creby <>", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyGreaterThan(String value) {
            addCriterion("creby >", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyGreaterThanOrEqualTo(String value) {
            addCriterion("creby >=", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyLessThan(String value) {
            addCriterion("creby <", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyLessThanOrEqualTo(String value) {
            addCriterion("creby <=", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyLike(String value) {
            addCriterion("creby like", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotLike(String value) {
            addCriterion("creby not like", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyIn(List<String> values) {
            addCriterion("creby in", values, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotIn(List<String> values) {
            addCriterion("creby not in", values, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyBetween(String value1, String value2) {
            addCriterion("creby between", value1, value2, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotBetween(String value1, String value2) {
            addCriterion("creby not between", value1, value2, "creby");
            return (Criteria) this;
        }

        public Criteria andLupbyIsNull() {
            addCriterion("lupby is null");
            return (Criteria) this;
        }

        public Criteria andLupbyIsNotNull() {
            addCriterion("lupby is not null");
            return (Criteria) this;
        }

        public Criteria andLupbyEqualTo(String value) {
            addCriterion("lupby =", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotEqualTo(String value) {
            addCriterion("lupby <>", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyGreaterThan(String value) {
            addCriterion("lupby >", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyGreaterThanOrEqualTo(String value) {
            addCriterion("lupby >=", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyLessThan(String value) {
            addCriterion("lupby <", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyLessThanOrEqualTo(String value) {
            addCriterion("lupby <=", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyLike(String value) {
            addCriterion("lupby like", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotLike(String value) {
            addCriterion("lupby not like", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyIn(List<String> values) {
            addCriterion("lupby in", values, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotIn(List<String> values) {
            addCriterion("lupby not in", values, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyBetween(String value1, String value2) {
            addCriterion("lupby between", value1, value2, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotBetween(String value1, String value2) {
            addCriterion("lupby not between", value1, value2, "lupby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drev
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 30 22:34:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}