package com.sg.cp.pojo;

import java.math.BigDecimal;
import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class Drev extends CommonPojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.drevid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Integer drevid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.transdate
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Date transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.itemid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.totalamt
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private BigDecimal totalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.dailyrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private BigDecimal dailyrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.monthlyrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private BigDecimal monthlyrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.monthcutoff
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Integer monthcutoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.prdrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private BigDecimal prdrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.prdstart
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Date prdstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drev.prdend
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Date prdend;

    public Integer getDrevid() {
        return drevid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.drevid
     *
     * @param drevid the value for drev.drevid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setDrevid(Integer drevid) {
        this.drevid = drevid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.transdate
     *
     * @return the value of drev.transdate
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.transdate
     *
     * @param transdate the value for drev.transdate
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.itemid
     *
     * @return the value of drev.itemid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.itemid
     *
     * @param itemid the value for drev.itemid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.totalamt
     *
     * @return the value of drev.totalamt
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public BigDecimal getTotalamt() {
        return totalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.totalamt
     *
     * @param totalamt the value for drev.totalamt
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setTotalamt(BigDecimal totalamt) {
        this.totalamt = totalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.dailyrev
     *
     * @return the value of drev.dailyrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public BigDecimal getDailyrev() {
        return dailyrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.dailyrev
     *
     * @param dailyrev the value for drev.dailyrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setDailyrev(BigDecimal dailyrev) {
        this.dailyrev = dailyrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.monthlyrev
     *
     * @return the value of drev.monthlyrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public BigDecimal getMonthlyrev() {
        return monthlyrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.monthlyrev
     *
     * @param monthlyrev the value for drev.monthlyrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setMonthlyrev(BigDecimal monthlyrev) {
        this.monthlyrev = monthlyrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.monthcutoff
     *
     * @return the value of drev.monthcutoff
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Integer getMonthcutoff() {
        return monthcutoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.monthcutoff
     *
     * @param monthcutoff the value for drev.monthcutoff
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setMonthcutoff(Integer monthcutoff) {
        this.monthcutoff = monthcutoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.prdrev
     *
     * @return the value of drev.prdrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public BigDecimal getPrdrev() {
        return prdrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.prdrev
     *
     * @param prdrev the value for drev.prdrev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setPrdrev(BigDecimal prdrev) {
        this.prdrev = prdrev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.prdstart
     *
     * @return the value of drev.prdstart
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Date getPrdstart() {
        return prdstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.prdstart
     *
     * @param prdstart the value for drev.prdstart
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setPrdstart(Date prdstart) {
        this.prdstart = prdstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drev.prdend
     *
     * @return the value of drev.prdend
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Date getPrdend() {
        return prdend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drev.prdend
     *
     * @param prdend the value for drev.prdend
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setPrdend(Date prdend) {
        this.prdend = prdend;
    }
}