package com.sg.cp.pojo;
import com.sg.cp.pojo.common.CommonPojo;

public class Fugp extends CommonPojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.fuctiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Integer fuctiongpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.functiongpname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String functiongpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.remark
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    
    public Integer getFuctiongpid() {
        return fuctiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.fuctiongpid
     *
     * @param fuctiongpid the value for fugp.fuctiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setFuctiongpid(Integer fuctiongpid) {
        this.fuctiongpid = fuctiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.functiongpname
     *
     * @return the value of fugp.functiongpname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getFunctiongpname() {
        return functiongpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.functiongpname
     *
     * @param functiongpname the value for fugp.functiongpname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setFunctiongpname(String functiongpname) {
        this.functiongpname = functiongpname == null ? null : functiongpname.trim();
    }
}