package com.sg.cp.pojo;

import java.io.Serializable;

public class Fugp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.fuctiongpid
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private Integer fuctiongpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.functiongpname
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private String functiongpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.active
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private Integer active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.readonly
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private Integer readonly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.credate
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.lupdate
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private Long lupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fugp.desc
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.fuctiongpid
     *
     * @return the value of fugp.fuctiongpid
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public Integer getFuctiongpid() {
        return fuctiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.fuctiongpid
     *
     * @param fuctiongpid the value for fugp.fuctiongpid
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setFuctiongpid(Integer fuctiongpid) {
        this.fuctiongpid = fuctiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.functiongpname
     *
     * @return the value of fugp.functiongpname
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public String getFunctiongpname() {
        return functiongpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.functiongpname
     *
     * @param functiongpname the value for fugp.functiongpname
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setFunctiongpname(String functiongpname) {
        this.functiongpname = functiongpname == null ? null : functiongpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.active
     *
     * @return the value of fugp.active
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.active
     *
     * @param active the value for fugp.active
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.readonly
     *
     * @return the value of fugp.readonly
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public Integer getReadonly() {
        return readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.readonly
     *
     * @param readonly the value for fugp.readonly
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setReadonly(Integer readonly) {
        this.readonly = readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.credate
     *
     * @return the value of fugp.credate
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.credate
     *
     * @param credate the value for fugp.credate
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.lupdate
     *
     * @return the value of fugp.lupdate
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.lupdate
     *
     * @param lupdate the value for fugp.lupdate
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fugp.desc
     *
     * @return the value of fugp.desc
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fugp.desc
     *
     * @param desc the value for fugp.desc
     *
     * @mbggenerated Sat Dec 22 10:59:11 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}