package com.sg.cp.pojo;

import java.io.Serializable;

public class Func implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.functionid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Integer functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.functionname
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private String functionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.desc
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.active
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.fuctiongpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    
    private Fugp fugp;
    
    private int fuctiongpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.credate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.lupdate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Long lupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.functionid
     *
     * @return the value of func.functionid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Integer getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.functionid
     *
     * @param functionid the value for func.functionid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setFunctionid(Integer functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.functionname
     *
     * @return the value of func.functionname
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public String getFunctionname() {
        return functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.functionname
     *
     * @param functionname the value for func.functionname
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setFunctionname(String functionname) {
        this.functionname = functionname == null ? null : functionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.desc
     *
     * @return the value of func.desc
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.desc
     *
     * @param desc the value for func.desc
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.active
     *
     * @return the value of func.active
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.active
     *
     * @param active the value for func.active
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.credate
     *
     * @return the value of func.credate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.credate
     *
     * @param credate the value for func.credate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.lupdate
     *
     * @return the value of func.lupdate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.lupdate
     *
     * @param lupdate the value for func.lupdate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }

	public Fugp getFugp() {
		return fugp;
	}

	public void setFugp(Fugp fugp) {
		this.fugp = fugp;
	}

	public int getFuctiongpid() {
		return fuctiongpid;
	}

	public void setFuctiongpid(int fuctiongpid) {
		this.fuctiongpid = fuctiongpid;
	}

	@Override
	public String toString() {
		return "Func [functionid=" + functionid + ", functionname=" + functionname + ", desc=" + desc + ", active="
				+ active + ", fugp=" + fugp + ", fuctiongpid=" + fuctiongpid + ", credate=" + credate + ", lupdate="
				+ lupdate + "]";
	}
    
    
}