package com.sg.cp.pojo;

import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class Func extends CommonPojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.functionid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Integer functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.functionname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String functionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.fuctiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Integer fuctiongpid;
   
    public Integer getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.functionid
     *
     * @param functionid the value for func.functionid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setFunctionid(Integer functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.functionname
     *
     * @return the value of func.functionname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getFunctionname() {
        return functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.functionname
     *
     * @param functionname the value for func.functionname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setFunctionname(String functionname) {
        this.functionname = functionname == null ? null : functionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.fuctiongpid
     *
     * @return the value of func.fuctiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public Integer getFuctiongpid() {
        return fuctiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.fuctiongpid
     *
     * @param fuctiongpid the value for func.fuctiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setFuctiongpid(Integer fuctiongpid) {
        this.fuctiongpid = fuctiongpid;
    }
}