package com.sg.cp.pojo;

import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class Hday extends CommonPojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hday.hdayid
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    private Integer hdayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hday.hdate
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    private Date hdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hday.isweekend
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    private String isweekend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hday.isholiday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    private String isholiday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hday.country
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    private String country;

    public Integer getHdayid() {
        return hdayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hday.hdayid
     *
     * @param hdayid the value for hday.hdayid
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public void setHdayid(Integer hdayid) {
        this.hdayid = hdayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hday.hdate
     *
     * @return the value of hday.hdate
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public Date getHdate() {
        return hdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hday.hdate
     *
     * @param hdate the value for hday.hdate
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public void setHdate(Date hdate) {
        this.hdate = hdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hday.isweekend
     *
     * @return the value of hday.isweekend
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public String getIsweekend() {
        return isweekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hday.isweekend
     *
     * @param isweekend the value for hday.isweekend
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public void setIsweekend(String isweekend) {
        this.isweekend = isweekend == null ? null : isweekend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hday.isholiday
     *
     * @return the value of hday.isholiday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public String getIsholiday() {
        return isholiday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hday.isholiday
     *
     * @param isholiday the value for hday.isholiday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public void setIsholiday(String isholiday) {
        this.isholiday = isholiday == null ? null : isholiday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hday.country
     *
     * @return the value of hday.country
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hday.country
     *
     * @param country the value for hday.country
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }
}