package com.sg.cp.pojo;

import java.math.BigDecimal;
import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class Item extends CommonPojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemname
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemcurr
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private String itemcurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemtype
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private String itemtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemlimit
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private BigDecimal itemlimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemlimitamt
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    private BigDecimal itemlimitamt;
   
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemid
     *
     * @param itemid the value for item.itemid
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemname
     *
     * @return the value of item.itemname
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemname
     *
     * @param itemname the value for item.itemname
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemcurr
     *
     * @return the value of item.itemcurr
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public String getItemcurr() {
        return itemcurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemcurr
     *
     * @param itemcurr the value for item.itemcurr
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemcurr(String itemcurr) {
        this.itemcurr = itemcurr == null ? null : itemcurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemtype
     *
     * @return the value of item.itemtype
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public String getItemtype() {
        return itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemtype
     *
     * @param itemtype the value for item.itemtype
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemtype(String itemtype) {
        this.itemtype = itemtype == null ? null : itemtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemlimit
     *
     * @return the value of item.itemlimit
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public BigDecimal getItemlimit() {
        return itemlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemlimit
     *
     * @param itemlimit the value for item.itemlimit
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemlimit(BigDecimal itemlimit) {
        this.itemlimit = itemlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemlimitamt
     *
     * @return the value of item.itemlimitamt
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public BigDecimal getItemlimitamt() {
        return itemlimitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemlimitamt
     *
     * @param itemlimitamt the value for item.itemlimitamt
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setItemlimitamt(BigDecimal itemlimitamt) {
        this.itemlimitamt = itemlimitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.remark
     *
     * @return the value of item.remark
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
}