package com.sg.cp.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public ItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemidIsNull() {
            addCriterion("itemid is null");
            return (Criteria) this;
        }

        public Criteria andItemidIsNotNull() {
            addCriterion("itemid is not null");
            return (Criteria) this;
        }

        public Criteria andItemidEqualTo(Integer value) {
            addCriterion("itemid =", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotEqualTo(Integer value) {
            addCriterion("itemid <>", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidGreaterThan(Integer value) {
            addCriterion("itemid >", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemid >=", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidLessThan(Integer value) {
            addCriterion("itemid <", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidLessThanOrEqualTo(Integer value) {
            addCriterion("itemid <=", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidIn(List<Integer> values) {
            addCriterion("itemid in", values, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotIn(List<Integer> values) {
            addCriterion("itemid not in", values, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidBetween(Integer value1, Integer value2) {
            addCriterion("itemid between", value1, value2, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotBetween(Integer value1, Integer value2) {
            addCriterion("itemid not between", value1, value2, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNull() {
            addCriterion("itemname is null");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNotNull() {
            addCriterion("itemname is not null");
            return (Criteria) this;
        }

        public Criteria andItemnameEqualTo(String value) {
            addCriterion("itemname =", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotEqualTo(String value) {
            addCriterion("itemname <>", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThan(String value) {
            addCriterion("itemname >", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThanOrEqualTo(String value) {
            addCriterion("itemname >=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThan(String value) {
            addCriterion("itemname <", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThanOrEqualTo(String value) {
            addCriterion("itemname <=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLike(String value) {
            addCriterion("itemname like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotLike(String value) {
            addCriterion("itemname not like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameIn(List<String> values) {
            addCriterion("itemname in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotIn(List<String> values) {
            addCriterion("itemname not in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameBetween(String value1, String value2) {
            addCriterion("itemname between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotBetween(String value1, String value2) {
            addCriterion("itemname not between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemcurrIsNull() {
            addCriterion("itemcurr is null");
            return (Criteria) this;
        }

        public Criteria andItemcurrIsNotNull() {
            addCriterion("itemcurr is not null");
            return (Criteria) this;
        }

        public Criteria andItemcurrEqualTo(String value) {
            addCriterion("itemcurr =", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrNotEqualTo(String value) {
            addCriterion("itemcurr <>", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrGreaterThan(String value) {
            addCriterion("itemcurr >", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrGreaterThanOrEqualTo(String value) {
            addCriterion("itemcurr >=", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrLessThan(String value) {
            addCriterion("itemcurr <", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrLessThanOrEqualTo(String value) {
            addCriterion("itemcurr <=", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrLike(String value) {
            addCriterion("itemcurr like", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrNotLike(String value) {
            addCriterion("itemcurr not like", value, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrIn(List<String> values) {
            addCriterion("itemcurr in", values, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrNotIn(List<String> values) {
            addCriterion("itemcurr not in", values, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrBetween(String value1, String value2) {
            addCriterion("itemcurr between", value1, value2, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemcurrNotBetween(String value1, String value2) {
            addCriterion("itemcurr not between", value1, value2, "itemcurr");
            return (Criteria) this;
        }

        public Criteria andItemtypeIsNull() {
            addCriterion("itemtype is null");
            return (Criteria) this;
        }

        public Criteria andItemtypeIsNotNull() {
            addCriterion("itemtype is not null");
            return (Criteria) this;
        }

        public Criteria andItemtypeEqualTo(String value) {
            addCriterion("itemtype =", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotEqualTo(String value) {
            addCriterion("itemtype <>", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeGreaterThan(String value) {
            addCriterion("itemtype >", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeGreaterThanOrEqualTo(String value) {
            addCriterion("itemtype >=", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeLessThan(String value) {
            addCriterion("itemtype <", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeLessThanOrEqualTo(String value) {
            addCriterion("itemtype <=", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeLike(String value) {
            addCriterion("itemtype like", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotLike(String value) {
            addCriterion("itemtype not like", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeIn(List<String> values) {
            addCriterion("itemtype in", values, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotIn(List<String> values) {
            addCriterion("itemtype not in", values, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeBetween(String value1, String value2) {
            addCriterion("itemtype between", value1, value2, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotBetween(String value1, String value2) {
            addCriterion("itemtype not between", value1, value2, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemlimitIsNull() {
            addCriterion("itemlimit is null");
            return (Criteria) this;
        }

        public Criteria andItemlimitIsNotNull() {
            addCriterion("itemlimit is not null");
            return (Criteria) this;
        }

        public Criteria andItemlimitEqualTo(BigDecimal value) {
            addCriterion("itemlimit =", value, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitNotEqualTo(BigDecimal value) {
            addCriterion("itemlimit <>", value, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitGreaterThan(BigDecimal value) {
            addCriterion("itemlimit >", value, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("itemlimit >=", value, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitLessThan(BigDecimal value) {
            addCriterion("itemlimit <", value, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("itemlimit <=", value, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitIn(List<BigDecimal> values) {
            addCriterion("itemlimit in", values, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitNotIn(List<BigDecimal> values) {
            addCriterion("itemlimit not in", values, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("itemlimit between", value1, value2, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("itemlimit not between", value1, value2, "itemlimit");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtIsNull() {
            addCriterion("itemlimitamt is null");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtIsNotNull() {
            addCriterion("itemlimitamt is not null");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtEqualTo(BigDecimal value) {
            addCriterion("itemlimitamt =", value, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtNotEqualTo(BigDecimal value) {
            addCriterion("itemlimitamt <>", value, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtGreaterThan(BigDecimal value) {
            addCriterion("itemlimitamt >", value, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("itemlimitamt >=", value, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtLessThan(BigDecimal value) {
            addCriterion("itemlimitamt <", value, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("itemlimitamt <=", value, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtIn(List<BigDecimal> values) {
            addCriterion("itemlimitamt in", values, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtNotIn(List<BigDecimal> values) {
            addCriterion("itemlimitamt not in", values, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("itemlimitamt between", value1, value2, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andItemlimitamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("itemlimitamt not between", value1, value2, "itemlimitamt");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCredateIsNull() {
            addCriterion("credate is null");
            return (Criteria) this;
        }

        public Criteria andCredateIsNotNull() {
            addCriterion("credate is not null");
            return (Criteria) this;
        }

        public Criteria andCredateEqualTo(Date value) {
            addCriterion("credate =", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateNotEqualTo(Date value) {
            addCriterion("credate <>", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateGreaterThan(Date value) {
            addCriterion("credate >", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateGreaterThanOrEqualTo(Date value) {
            addCriterion("credate >=", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateLessThan(Date value) {
            addCriterion("credate <", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateLessThanOrEqualTo(Date value) {
            addCriterion("credate <=", value, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateIn(List<Date> values) {
            addCriterion("credate in", values, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateNotIn(List<Date> values) {
            addCriterion("credate not in", values, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateBetween(Date value1, Date value2) {
            addCriterion("credate between", value1, value2, "credate");
            return (Criteria) this;
        }

        public Criteria andCredateNotBetween(Date value1, Date value2) {
            addCriterion("credate not between", value1, value2, "credate");
            return (Criteria) this;
        }

        public Criteria andLupdateIsNull() {
            addCriterion("lupdate is null");
            return (Criteria) this;
        }

        public Criteria andLupdateIsNotNull() {
            addCriterion("lupdate is not null");
            return (Criteria) this;
        }

        public Criteria andLupdateEqualTo(Date value) {
            addCriterion("lupdate =", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateNotEqualTo(Date value) {
            addCriterion("lupdate <>", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateGreaterThan(Date value) {
            addCriterion("lupdate >", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateGreaterThanOrEqualTo(Date value) {
            addCriterion("lupdate >=", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateLessThan(Date value) {
            addCriterion("lupdate <", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateLessThanOrEqualTo(Date value) {
            addCriterion("lupdate <=", value, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateIn(List<Date> values) {
            addCriterion("lupdate in", values, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateNotIn(List<Date> values) {
            addCriterion("lupdate not in", values, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateBetween(Date value1, Date value2) {
            addCriterion("lupdate between", value1, value2, "lupdate");
            return (Criteria) this;
        }

        public Criteria andLupdateNotBetween(Date value1, Date value2) {
            addCriterion("lupdate not between", value1, value2, "lupdate");
            return (Criteria) this;
        }

        public Criteria andCrebyIsNull() {
            addCriterion("creby is null");
            return (Criteria) this;
        }

        public Criteria andCrebyIsNotNull() {
            addCriterion("creby is not null");
            return (Criteria) this;
        }

        public Criteria andCrebyEqualTo(String value) {
            addCriterion("creby =", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotEqualTo(String value) {
            addCriterion("creby <>", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyGreaterThan(String value) {
            addCriterion("creby >", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyGreaterThanOrEqualTo(String value) {
            addCriterion("creby >=", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyLessThan(String value) {
            addCriterion("creby <", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyLessThanOrEqualTo(String value) {
            addCriterion("creby <=", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyLike(String value) {
            addCriterion("creby like", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotLike(String value) {
            addCriterion("creby not like", value, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyIn(List<String> values) {
            addCriterion("creby in", values, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotIn(List<String> values) {
            addCriterion("creby not in", values, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyBetween(String value1, String value2) {
            addCriterion("creby between", value1, value2, "creby");
            return (Criteria) this;
        }

        public Criteria andCrebyNotBetween(String value1, String value2) {
            addCriterion("creby not between", value1, value2, "creby");
            return (Criteria) this;
        }

        public Criteria andLupbyIsNull() {
            addCriterion("lupby is null");
            return (Criteria) this;
        }

        public Criteria andLupbyIsNotNull() {
            addCriterion("lupby is not null");
            return (Criteria) this;
        }

        public Criteria andLupbyEqualTo(String value) {
            addCriterion("lupby =", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotEqualTo(String value) {
            addCriterion("lupby <>", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyGreaterThan(String value) {
            addCriterion("lupby >", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyGreaterThanOrEqualTo(String value) {
            addCriterion("lupby >=", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyLessThan(String value) {
            addCriterion("lupby <", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyLessThanOrEqualTo(String value) {
            addCriterion("lupby <=", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyLike(String value) {
            addCriterion("lupby like", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotLike(String value) {
            addCriterion("lupby not like", value, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyIn(List<String> values) {
            addCriterion("lupby in", values, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotIn(List<String> values) {
            addCriterion("lupby not in", values, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyBetween(String value1, String value2) {
            addCriterion("lupby between", value1, value2, "lupby");
            return (Criteria) this;
        }

        public Criteria andLupbyNotBetween(String value1, String value2) {
            addCriterion("lupby not between", value1, value2, "lupby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 30 22:34:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}