package com.sg.cp.pojo;

import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class Uscr extends CommonPojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.userid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.password
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String password;

    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.userid
     *
     * @param userid the value for uscr.userid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.password
     *
     * @return the value of uscr.password
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.password
     *
     * @param password the value for uscr.password
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}