package com.sg.cp.pojo;

import java.io.Serializable;

public class Uscr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.password
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long lupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String creby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uscr.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String lupby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.userid
     *
     * @return the value of uscr.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.userid
     *
     * @param userid the value for uscr.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.password
     *
     * @return the value of uscr.password
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.password
     *
     * @param password the value for uscr.password
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.remark
     *
     * @return the value of uscr.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.remark
     *
     * @param remark the value for uscr.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.status
     *
     * @return the value of uscr.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.status
     *
     * @param status the value for uscr.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.credate
     *
     * @return the value of uscr.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.credate
     *
     * @param credate the value for uscr.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.lupdate
     *
     * @return the value of uscr.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.lupdate
     *
     * @param lupdate the value for uscr.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.creby
     *
     * @return the value of uscr.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getCreby() {
        return creby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.creby
     *
     * @param creby the value for uscr.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCreby(String creby) {
        this.creby = creby == null ? null : creby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uscr.lupby
     *
     * @return the value of uscr.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getLupby() {
        return lupby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uscr.lupby
     *
     * @param lupby the value for uscr.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupby(String lupby) {
        this.lupby = lupby == null ? null : lupby.trim();
    }
}