package com.sg.cp.pojo;

import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class UsgpFugp extends CommonPojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp_fugp.usgpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Integer usgpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp_fugp.functiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Integer functiongpid;

    public Integer getUsgpid() {
        return usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp_fugp.usgpid
     *
     * @param usgpid the value for usgp_fugp.usgpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setUsgpid(Integer usgpid) {
        this.usgpid = usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp_fugp.functiongpid
     *
     * @return the value of usgp_fugp.functiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public Integer getFunctiongpid() {
        return functiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp_fugp.functiongpid
     *
     * @param functiongpid the value for usgp_fugp.functiongpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setFunctiongpid(Integer functiongpid) {
        this.functiongpid = functiongpid;
    }
}