package com.sg.cp.pojo;

import java.io.Serializable;

public class Usgp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.usgpid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Integer usgpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.usgpname
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String usgpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.leaderid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String leaderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long lupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String creby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String lupby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.usgpid
     *
     * @return the value of usgp.usgpid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Integer getUsgpid() {
        return usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.usgpid
     *
     * @param usgpid the value for usgp.usgpid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setUsgpid(Integer usgpid) {
        this.usgpid = usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.usgpname
     *
     * @return the value of usgp.usgpname
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getUsgpname() {
        return usgpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.usgpname
     *
     * @param usgpname the value for usgp.usgpname
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setUsgpname(String usgpname) {
        this.usgpname = usgpname == null ? null : usgpname.trim();
    }

    public String getLeaderid() {
		return leaderid;
	}

	public void setLeaderid(String leaderid) {
		this.leaderid = leaderid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.remark
     *
     * @return the value of usgp.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.remark
     *
     * @param remark the value for usgp.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.status
     *
     * @return the value of usgp.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.status
     *
     * @param status the value for usgp.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.credate
     *
     * @return the value of usgp.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.credate
     *
     * @param credate the value for usgp.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.lupdate
     *
     * @return the value of usgp.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.lupdate
     *
     * @param lupdate the value for usgp.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.creby
     *
     * @return the value of usgp.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getCreby() {
        return creby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.creby
     *
     * @param creby the value for usgp.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCreby(String creby) {
        this.creby = creby == null ? null : creby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp.lupby
     *
     * @return the value of usgp.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getLupby() {
        return lupby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp.lupby
     *
     * @param lupby the value for usgp.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupby(String lupby) {
        this.lupby = lupby == null ? null : lupby.trim();
    }
}