package com.sg.cp.pojo;

public class UsgpFugp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp_fugp.usgpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Integer usgpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp_fugp.functiongpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Integer functiongpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp_fugp.credate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usgp_fugp.lupdate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    private Long lupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp_fugp.usgpid
     *
     * @return the value of usgp_fugp.usgpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Integer getUsgpid() {
        return usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp_fugp.usgpid
     *
     * @param usgpid the value for usgp_fugp.usgpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setUsgpid(Integer usgpid) {
        this.usgpid = usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp_fugp.functiongpid
     *
     * @return the value of usgp_fugp.functiongpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Integer getFunctiongpid() {
        return functiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp_fugp.functiongpid
     *
     * @param functiongpid the value for usgp_fugp.functiongpid
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setFunctiongpid(Integer functiongpid) {
        this.functiongpid = functiongpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp_fugp.credate
     *
     * @return the value of usgp_fugp.credate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp_fugp.credate
     *
     * @param credate the value for usgp_fugp.credate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usgp_fugp.lupdate
     *
     * @return the value of usgp_fugp.lupdate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usgp_fugp.lupdate
     *
     * @param lupdate the value for usgp_fugp.lupdate
     *
     * @mbggenerated Sat Dec 22 10:25:43 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }
}