package com.sg.cp.pojo;

import java.util.Date;
import java.util.List;

import com.sg.cp.pojo.common.CommonPojo;

public class Usgp extends CommonPojo {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column usgp.usgpid
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	private Integer usgpid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column usgp.usgpname
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	private String usgpname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column usgp.leaderid
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	private String leaderid;

	public Integer getUsgpid() {
		return usgpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column usgp.usgpid
	 *
	 * @param usgpid the value for usgp.usgpid
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	public void setUsgpid(Integer usgpid) {
		this.usgpid = usgpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column usgp.usgpname
	 *
	 * @return the value of usgp.usgpname
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	public String getUsgpname() {
		return usgpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column usgp.usgpname
	 *
	 * @param usgpname the value for usgp.usgpname
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	public void setUsgpname(String usgpname) {
		this.usgpname = usgpname == null ? null : usgpname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column usgp.leaderid
	 *
	 * @return the value of usgp.leaderid
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	public String getLeaderid() {
		return leaderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column usgp.leaderid
	 *
	 * @param leaderid the value for usgp.leaderid
	 *
	 * @mbggenerated Sat Dec 29 16:19:32 CST 2018
	 */
	public void setLeaderid(String leaderid) {
		this.leaderid = leaderid == null ? null : leaderid.trim();
	}

	/* Below self defined */
	private List<Uspf> uspfs;

	public List<Uspf> getUspfs() {
		return uspfs;
	}

	public void setUspfs(List<Uspf> uspfs) {
		this.uspfs = uspfs;
	}

}