package com.sg.cp.pojo;

import java.util.Date;

import com.sg.cp.pojo.common.CommonPojo;

public class UspfGp extends CommonPojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.userid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.usgpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Integer usgpid;

    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.userid
     *
     * @param userid the value for uspf_gp.userid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.usgpid
     *
     * @return the value of uspf_gp.usgpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public Integer getUsgpid() {
        return usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.usgpid
     *
     * @param usgpid the value for uspf_gp.usgpid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setUsgpid(Integer usgpid) {
        this.usgpid = usgpid;
    }
}