package com.sg.cp.pojo;

import java.util.Date;
import java.util.List;

import com.sg.cp.pojo.common.CommonPojo;

public class Uspf extends CommonPojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.userid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.reporterid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String reporterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.realname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.gender
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.email
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.telno
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String telno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.wechatno
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String wechatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.addr
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.dob
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Date dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.expirydate
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Date expirydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.designation
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String designation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.terminationdate
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private Date terminationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.remark
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    private String remark;
    
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.userid
     *
     * @param userid the value for uspf.userid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.reporterid
     *
     * @return the value of uspf.reporterid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getReporterid() {
        return reporterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.reporterid
     *
     * @param reporterid the value for uspf.reporterid
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setReporterid(String reporterid) {
        this.reporterid = reporterid == null ? null : reporterid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.realname
     *
     * @return the value of uspf.realname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.realname
     *
     * @param realname the value for uspf.realname
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.gender
     *
     * @return the value of uspf.gender
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.gender
     *
     * @param gender the value for uspf.gender
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.email
     *
     * @return the value of uspf.email
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.email
     *
     * @param email the value for uspf.email
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.telno
     *
     * @return the value of uspf.telno
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.telno
     *
     * @param telno the value for uspf.telno
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.wechatno
     *
     * @return the value of uspf.wechatno
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getWechatno() {
        return wechatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.wechatno
     *
     * @param wechatno the value for uspf.wechatno
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setWechatno(String wechatno) {
        this.wechatno = wechatno == null ? null : wechatno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.addr
     *
     * @return the value of uspf.addr
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.addr
     *
     * @param addr the value for uspf.addr
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.dob
     *
     * @return the value of uspf.dob
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.dob
     *
     * @param dob the value for uspf.dob
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.expirydate
     *
     * @return the value of uspf.expirydate
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public Date getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.expirydate
     *
     * @param expirydate the value for uspf.expirydate
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.designation
     *
     * @return the value of uspf.designation
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.designation
     *
     * @param designation the value for uspf.designation
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setDesignation(String designation) {
        this.designation = designation == null ? null : designation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.terminationdate
     *
     * @return the value of uspf.terminationdate
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public Date getTerminationdate() {
        return terminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.terminationdate
     *
     * @param terminationdate the value for uspf.terminationdate
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setTerminationdate(Date terminationdate) {
        this.terminationdate = terminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.remark
     *
     * @return the value of uspf.remark
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.remark
     *
     * @param remark the value for uspf.remark
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    
    
    
    @Override
	public String toString() {
		return "Uspf [userid=" + userid + ", reporterid=" + reporterid + ", realname=" + realname + ", gender=" + gender
				+ ", email=" + email + ", telno=" + telno + ", wechatno=" + wechatno + ", addr=" + addr + ", dob=" + dob
				+ ", expirydate=" + expirydate + ", designation=" + designation + ", terminationdate=" + terminationdate
				+ ", remark=" + remark + ", usgps=" + usgps + ", uscr=" + uscr + ", usgpDesc=" + usgpDesc + "]";
	}



	/*--------Self Defined----------*/
    private List<Usgp> usgps; 
    
   	public List<Usgp> getUsgps() {
   		return usgps;
   	}

   	public void setUsgps(List<Usgp> usgps) {
   		this.usgps = usgps;
   	}
   	
   	private Uscr uscr;
   	
   	public Uscr getUscr() {
		return uscr;
	}

	public void setUscr(Uscr uscr) {
		this.uscr = uscr;
	}

	private String usgpDesc;
	
	public String getUsgpDesc() {
		return usgpDesc;
	}

	public void setUsgpDesc(String usgpDesc) {
		this.usgpDesc = usgpDesc;
	}

	
}