package com.sg.cp.pojo;

import java.io.Serializable;

public class Uspf implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.reporterid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String reporterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.realname
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.gender
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.email
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.telno
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String telno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.wechatno
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String wechatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.addr
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.dob
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Integer dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.expirydate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Integer expirydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.designation
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String designation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.terminationdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long terminationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long lupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String creby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String lupby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.userid
     *
     * @return the value of uspf.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.userid
     *
     * @param userid the value for uspf.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.reporterid
     *
     * @return the value of uspf.reporterid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getReporterid() {
        return reporterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.reporterid
     *
     * @param reporterid the value for uspf.reporterid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setReporterid(String reporterid) {
        this.reporterid = reporterid == null ? null : reporterid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.realname
     *
     * @return the value of uspf.realname
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.realname
     *
     * @param realname the value for uspf.realname
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.gender
     *
     * @return the value of uspf.gender
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.gender
     *
     * @param gender the value for uspf.gender
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.email
     *
     * @return the value of uspf.email
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.email
     *
     * @param email the value for uspf.email
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.telno
     *
     * @return the value of uspf.telno
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.telno
     *
     * @param telno the value for uspf.telno
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.wechatno
     *
     * @return the value of uspf.wechatno
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getWechatno() {
        return wechatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.wechatno
     *
     * @param wechatno the value for uspf.wechatno
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setWechatno(String wechatno) {
        this.wechatno = wechatno == null ? null : wechatno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.addr
     *
     * @return the value of uspf.addr
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.addr
     *
     * @param addr the value for uspf.addr
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.dob
     *
     * @return the value of uspf.dob
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Integer getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.dob
     *
     * @param dob the value for uspf.dob
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setDob(Integer dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.expirydate
     *
     * @return the value of uspf.expirydate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Integer getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.expirydate
     *
     * @param expirydate the value for uspf.expirydate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setExpirydate(Integer expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.designation
     *
     * @return the value of uspf.designation
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.designation
     *
     * @param designation the value for uspf.designation
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setDesignation(String designation) {
        this.designation = designation == null ? null : designation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.status
     *
     * @return the value of uspf.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.status
     *
     * @param status the value for uspf.status
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.terminationdate
     *
     * @return the value of uspf.terminationdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getTerminationdate() {
        return terminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.terminationdate
     *
     * @param terminationdate the value for uspf.terminationdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setTerminationdate(Long terminationdate) {
        this.terminationdate = terminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.credate
     *
     * @return the value of uspf.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.credate
     *
     * @param credate the value for uspf.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.lupdate
     *
     * @return the value of uspf.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.lupdate
     *
     * @param lupdate the value for uspf.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.remark
     *
     * @return the value of uspf.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.remark
     *
     * @param remark the value for uspf.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.creby
     *
     * @return the value of uspf.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getCreby() {
        return creby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.creby
     *
     * @param creby the value for uspf.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCreby(String creby) {
        this.creby = creby == null ? null : creby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf.lupby
     *
     * @return the value of uspf.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getLupby() {
        return lupby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf.lupby
     *
     * @param lupby the value for uspf.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupby(String lupby) {
        this.lupby = lupby == null ? null : lupby.trim();
    }
}