package com.sg.cp.pojo;

import java.io.Serializable;

public class UspfGp implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.usgpid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Integer usgpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long credate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private Long lupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String creby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uspf_gp.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    private String lupby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.userid
     *
     * @return the value of uspf_gp.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.userid
     *
     * @param userid the value for uspf_gp.userid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.usgpid
     *
     * @return the value of uspf_gp.usgpid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Integer getUsgpid() {
        return usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.usgpid
     *
     * @param usgpid the value for uspf_gp.usgpid
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setUsgpid(Integer usgpid) {
        this.usgpid = usgpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.credate
     *
     * @return the value of uspf_gp.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getCredate() {
        return credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.credate
     *
     * @param credate the value for uspf_gp.credate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCredate(Long credate) {
        this.credate = credate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.lupdate
     *
     * @return the value of uspf_gp.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public Long getLupdate() {
        return lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.lupdate
     *
     * @param lupdate the value for uspf_gp.lupdate
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupdate(Long lupdate) {
        this.lupdate = lupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.remark
     *
     * @return the value of uspf_gp.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.remark
     *
     * @param remark the value for uspf_gp.remark
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.creby
     *
     * @return the value of uspf_gp.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getCreby() {
        return creby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.creby
     *
     * @param creby the value for uspf_gp.creby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setCreby(String creby) {
        this.creby = creby == null ? null : creby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uspf_gp.lupby
     *
     * @return the value of uspf_gp.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public String getLupby() {
        return lupby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uspf_gp.lupby
     *
     * @param lupby the value for uspf_gp.lupby
     *
     * @mbggenerated Fri Nov 30 21:51:12 CST 2018
     */
    public void setLupby(String lupby) {
        this.lupby = lupby == null ? null : lupby.trim();
    }
}