package com.sg.cp.mapper;

import com.sg.cp.pojo.Drev;
import com.sg.cp.pojo.DrevExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrevMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int countByExample(DrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int deleteByExample(DrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int insert(Drev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int insertSelective(Drev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    List<Drev> selectByExample(DrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Drev record, @Param("example") DrevExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drev
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int updateByExample(@Param("record") Drev record, @Param("example") DrevExample example);
    
}