package com.sg.cp.mapper;

import com.sg.cp.pojo.Fugp;
import com.sg.cp.pojo.FugpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FugpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int countByExample(FugpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int deleteByExample(FugpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int insert(Fugp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int insertSelective(Fugp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    List<Fugp> selectByExample(FugpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fugp record, @Param("example") FugpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fugp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int updateByExample(@Param("record") Fugp record, @Param("example") FugpExample example);
}