package com.sg.cp.mapper;

import com.sg.cp.pojo.Hday;
import com.sg.cp.pojo.HdayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HdayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    int countByExample(HdayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    int deleteByExample(HdayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    int insert(Hday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    int insertSelective(Hday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    List<Hday> selectByExample(HdayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Hday record, @Param("example") HdayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hday
     *
     * @mbggenerated Sun Dec 30 21:04:11 CST 2018
     */
    int updateByExample(@Param("record") Hday record, @Param("example") HdayExample example);
}