package com.sg.cp.mapper;

import com.sg.cp.pojo.Item;
import com.sg.cp.pojo.ItemExample;
import com.sg.cp.pojo.Uspf;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Sun Dec 30 22:34:07 CST 2018
     */
    int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);
    
    /*-------------------self defined------------------*/

    List<Item> selectItemUnderProduct(@Param("prodname") String prodname,@Param("itemname") String itemname);
}