package com.sg.cp.mapper;

import com.sg.cp.pojo.Usgp;
import com.sg.cp.pojo.UsgpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsgpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int countByExample(UsgpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int deleteByExample(UsgpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int insert(Usgp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int insertSelective(Usgp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    List<Usgp> selectByExample(UsgpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Usgp record, @Param("example") UsgpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usgp
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int updateByExample(@Param("record") Usgp record, @Param("example") UsgpExample example);
    
    /*--Below self defined--*/
    List<Usgp> selectusgpandmatchingusers(@Param("status") String status);
}