package com.sg.cp.mapper;

import com.sg.cp.pojo.Uspf;
import com.sg.cp.pojo.UspfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UspfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int countByExample(UspfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int deleteByExample(UspfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int insert(Uspf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int insertSelective(Uspf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    List<Uspf> selectByExample(UspfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Uspf record, @Param("example") UspfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uspf
     *
     * @mbggenerated Sat Dec 29 16:19:32 CST 2018
     */
    int updateByExample(@Param("record") Uspf record, @Param("example") UspfExample example);
    
    
    /*-------------------self defined------------------*/

    List<Uspf> selectuspfandusgp(@Param("status") String status);
    
    List<Uspf> selectuspfanduscr(@Param("status") String status,@Param("userid") String userid);
}